Ensure correct timezone is used
frankkoornstra/elastic-apm-agent pull request #20
Opened 2018-08-17 09:05 UTC by mikolfaro

If PHP does not use UTC timezone, the timestamps sent are wrong.
Converted `Timestamp` to UTC timezone during serialization to ensure that the timestamps sent to APM are correct.

## Description
Sending timestamp `2018-01-15T12:00:00.000000Z` to APM API means that the event happened at midday in UTC timezone, as per [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
Therefore if PHP is not using UTC the timestamp must be converted before sending it.

2018-09-05 13:01 UTC, frankkoornstra requested changes
He, thanks for your contribution! Somethings' must've gone wrong with my notifications/email because this is the first time I see it, sorry 😕

I left some comments on the code but I'd also like to ask  you to browse over the [contributing document](https://github.com/frankkoornstra/elastic-apm-agent/blob/master/.github/CONTRIBUTING.md), especially the part on atomic commits.

If you feel uncomfortable reworking your commits, tell me and I'll make sure that your work gets in by cloning your branch and reworking the commits myself.

2018-09-05 13:01 UTC, frankkoornstra commented on docker/Dockerfile-php
> +RUN apt-get update \
Why do we need these extra packages?

2018-09-05 13:01 UTC, frankkoornstra commented on src/Message/Timestamp.php
> -        $me = clone $this;
This is done to make sure that changes are always applied to a copy of the data. Immutability is one of the cornerstones of this library so please leave this in.

2018-09-05 13:01 UTC, frankkoornstra commented on src/Message/Timestamp.php
> +        $utc = $this->setTimezone(new \DateTimeZone('UTC'));
Always setting the timezone to UTC is a big assumption, what's your reasoning?

2018-09-05 13:01 UTC, frankkoornstra commented on tests/Unit/Message/TimestampTest.php
> +        date_default_timezone_set($this->oldTimeZone);
Nice

2018-09-05 14:25 UTC, mikolfaro commented
Hi @frankkoornstra , thank you for replying

This PR fixes a bug I noticed looking at the APM data: timestamps have wrong offset, due to the format used in serialization. I would like to submit a new (cleaner) PR with a clear explanation of what and why this happens.

2018-09-05 14:40 UTC, frankkoornstra commented
Ok, cool, thanks! I'll close this one then and look forward to seeing the other one 😎

2018-09-05 14:40 UTC, closed without merging

2018-09-06 09:45 UTC, mikolfaro commented
I created a new PR https://github.com/frankkoornstra/elastic-apm-agent/pull/22